name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        STEPPER_TYPE: [0, 1, 2]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run PlatformIO
      run: platformio run
      env:
        PLATFORMIO_BUILD_FLAGS: -DSTEPPER_TYPE${{ matrix.STEPPER_TYPE }}
